### ISSUE TITLE
How to bypass the cors error

### ISSUE THREAD

**Issue by Zaid944** [akarsh1995/leetcode-graphql-queries#3]
Got this error
Access to XMLHttpRequest at 'https://leetcode.com/graphql/' from origin 'http://localhost:5173' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by RC1092** [comment]
same issue here. let me know if u find any fix.

**Comment by akarsh1995** [comment]
Make sure Origin is set to `https://leetcode.com`

![image](https://github.com/akarsh1995/leetcode-graphql-queries/assets/25827628/a425ab3a-3968-490e-b21a-931718ca7e78)

**Comment by akarsh1995** [comment]
Authenticated requests must have these headers

![image](https://github.com/akarsh1995/leetcode-graphql-queries/assets/25827628/dbeba354-81b3-4649-835c-06530716cc8f)

**Comment by RC1092** [comment]
> Make sure Origin is set to `https://leetcode.com`
> 
> ![image](https://private-user-images.githubusercontent.com/25827628/299645085-a425ab3a-3968-490e-b21a-931718ca7e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2Mzk5NjAsIm5iZiI6MTcwNjYzOTY2MCwicGF0aCI6Ii8yNTgyNzYyOC8yOTk2NDUwODUtYTQyNWFiM2EtMzk2OC00OTBlLWIyMWEtOTMxNzE4Y2E3ZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE4MzQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNjNjOTE4YzU5ZWYzNDhhYzU1M2IyZWRkNDNmOGQ1NDQ5NDU5NjY1MGY3OThmMjdlODg1OTRmZGIyM2E5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZXrJwseoBTJaF3eiGHgFPGXeO4v2PDOOo_RsCuRKG_o)

How do i set it .. iam still getting preflight error
