### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by RobinKumar5986** [akarsh1995/leetcode-graphql-queries#6]
curl --location 'https://leetcode.com/graphql/' \
--header 'Content-Type: application/json' \
--header 'Cookie: LEETCODE_SESSION=<LEETCODE_SESSION>; csrftoken=<csrftoken>' \
--data '{"query":"query problemsetQuestionList($categorySlug: String, $limit: Int, $skip: Int, $filters: QuestionListFilterInput) {\n  problemsetQuestionList: questionList(\n    categorySlug: $categorySlug\n    limit: $limit\n    skip: $skip\n    filters: $filters\n  ) {\n    total: totalNum\n    questions: data {\n      acRate\n      difficulty\n      freqBar\n      frontendQuestionId: questionFrontendId\n      isFavor\n      paidOnly: isPaidOnly\n      status\n      title\n      titleSlug\n      topicTags {\n        name\n        id\n        slug\n      }\n      hasSolution\n      hasVideoSolution\n    }\n  }\n}","variables":{"categorySlug":"","skip":0,"limit":50,"filters":{}}}'

```
can you tell me how this API is working even tho I have not provided any token and leetcode session ? Is this working because I am already login in the leet code ?? 

```
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/dd93db73-478c-413f-a6eb-60945b839d80">
check in  this I have completely removed the parameter parameter but its still working its wired can you explain this behaviour ?

**Comment by akarsh1995** [comment]
You're right it works. However the fields that are private to you like status won't be visible.

**Comment by RobinKumar5986** [comment]
oo ok got it thanks.

**Comment by RobinKumar5986** [comment]
oo ok got it thanks.
